### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by grammakov** [davidesantangelo/emailhunter#2]
I understand there is an API limitation to when the amount of emails is over 100. How can i specify to use offset in the API call? Thanks!

**Comment by davidesantangelo** [comment]
done! Thanks

**Comment by grammakov** [comment]
@davidesantangelo  so how can one use it? :)

**Comment by davidesantangelo** [comment]
email_hunter = EmailHunter.new(key)
email_hunter.search('google.com', {offset: 10})
