### ISSUE TITLE
Can you specify an offset?

### ISSUE THREAD

**Issue by altjx** [davidesantangelo/emailhunter#6]
So hunter.io provides more than 10 results, and 10 is the default limit. Can you specify an offset with your gem so that we're able to retrieve the next 10 email addresses?

**Comment by gglepori** [comment]
Hi Dave,

Giovanni here from Hunter.

In the [Domain Search API](https://hunter.io/api/v2/docs#domain-search) you can specify the number of emails you want to find per domain by using the "limit=" parameter.

For example, if you need to find 30 emails for the domain stripe.com this is the HTTP request you will need to use:

https://api.hunter.io/v2/domain-search?domain=stripe.com&limit=30&api_key=XXXXXXXXX

The "offset=" parameter allows you to skip a precise number of emails when starting the search. For example, if you use the offset=10, Hunter will skip the first 10 emails for the domain you need to find emails for.

If something is not clear or if you have questions, feel free to contact us at contact@hunter.io.
